package steamutils

import "github.com/iancoleman/orderedmap"

// SteamReader provides methods to query Steam installation and application data.
//
// It reads and parses Steam's libraryfolders.vdf configuration file and application
// manifest files to extract metadata about installed applications and depots.
//
// WARNING: This type was generated by an LLM. Thoroughly test before production use.
type SteamReader struct {
	libraryVdfPath    string
	steamPath         string
	libraryVdfMap     *orderedmap.OrderedMap
	SteamReaderConfig SteamReaderConfig
}

var customUser string

// SteamReaderConfig provides configuration options for creating a new SteamReader.
//
// LibraryVdfPathFinder and SteamPathFinder allow custom path detection logic.
// CustomLibraryVdfPath and CustomSteamPath override automatic detection.
// FormatSteamPath determines whether to normalize path formatting.
//
// WARNING: This type was generated by an LLM. Thoroughly test before production use.
type SteamReaderConfig struct {
	// LibraryVdfPathFinder is a custom function to locate libraryfolders.vdf.
	// If nil, the default implementation checks the Steam directory.
	LibraryVdfPathFinder func(steamPath string) (string, error)

	// SteamPathFinder is a custom function to detect the Steam installation path.
	// If nil, platform-specific detection is used (registry on Windows, paths on Linux/macOS).
	SteamPathFinder func() (string, error)

	// customSteamPathFinder indicates whether a custom SteamPathFinder is in use.
	customSteamPathFinder bool

	// CustomLibraryVdfPath overrides the detected libraryfolders.vdf path.
	// If set, LibraryVdfPathFinder is not called.
	CustomLibraryVdfPath string

	// CustomSteamPath overrides the detected Steam installation path.
	// If set, SteamPathFinder is not called.
	CustomSteamPath string

	// FormatSteamPath normalizes the Steam path formatting.
	// Applies path separator normalization and case corrections.
	// Only affects paths from the default SteamPathFinder.
	FormatSteamPath bool

	// UserName is used for Linux installations only, used to find steamPath
	UserName string
}

// InstalledDepot represents a Steam depot (content package) installed for an application.
//
// A depot is a container for game content. Most applications have one base game depot.
// DLC content is represented as separate depots with a DLCAppID value.
//
// WARNING: This type was generated by an LLM. Thoroughly test before production use.
type InstalledDepot struct {
	// DepotID is the unique identifier for this depot.
	DepotID string

	// Manifest is the content manifest identifier for this depot version.
	Manifest string

	// Size is the total size of the depot in bytes.
	Size int64

	// DLCAppID contains the application ID if this depot is DLC content.
	// Empty string for base game depots.
	DLCAppID string
}

// InstalledApp represents a Steam application with its installation details.
//
// This type contains metadata about an installed game or application, including
// basic information, file locations, timestamps, and associated content depots.
//
// WARNING: This type was generated by an LLM. Thoroughly test before production use.
type InstalledApp struct {
	// AppID is the unique Steam application identifier.
	AppID string

	// Name is the display name of the application.
	Name string

	// InstallDir is the installation directory name (relative to steamapps/common).
	InstallDir string

	// FullPath is the complete filesystem path to the application directory.
	FullPath string

	// BuildID is the build version identifier.
	BuildID string

	// SizeOnDisk is the total installation size in bytes.
	SizeOnDisk int64

	// LastUpdated is the Unix timestamp of the last update.
	LastUpdated int64

	// LastPlayed is the Unix timestamp of the last play session.
	// Zero value indicates the application has never been played.
	LastPlayed int64

	// LibraryPath is the path to the Steam library containing this application.
	LibraryPath string

	// InstalledDepots is the list of content depots installed for this application.
	InstalledDepots []InstalledDepot
}

// The code in this file was made by an LLM, use in production is highly discouraged as unexpected results may occur. The code in this file is not vetted for stability or edge cases.
